project_name: loophole
before:
  hooks:
    - go mod download
builds:
- id: loophole
  binary: loophole
  goos:
  - linux
  - darwin
  - windows
  goarch:
  - 386
  - amd64
  - arm
  - arm64
archives:
- replacements:
    386: i386
  format_overrides:
  - goos: windows
    format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
