project_name: loophole

env:
  - GO111MODULE=on

before:
  hooks:
    - go mod download
    
builds:
- id: loophole-cli
  binary: loophole
  goos:
    - linux
    - darwin
  goarch:
    - 386
    - amd64
    - arm
    - arm64
  goarm:
    - 6
    - 7
  mod_timestamp: "{{ .CommitTimestamp }}"
  ldflags:
    - -s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}}
- id: loophole-cli-win
  binary: loophole
  goos:
    - windows
  goarch:
    - 386
    - amd64
  goarm:
    - 6
    - 7
  mod_timestamp: "{{ .CommitTimestamp }}"
  ldflags:
    - -s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}}

- id: loophole-desktop
  binary: loophole-desktop
  goos:
    - darwin
    - linux
  goarch:
    - amd64
    - 386
  mod_timestamp: "{{ .CommitTimestamp }}"
  ldflags:
    - -s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}}
  flags:
  - -tags=desktop

- id: loophole-desktop-win
  binary: loophole-desktop
  goos:
    - windows
  goarch:
    - amd64
    - 386
  mod_timestamp: "{{ .CommitTimestamp }}"
  ldflags:
    - -s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}} -H windowsgui
  flags:
  - -tags=desktop

archives:
  - id: cli
    builds:
      - loophole-cli
      - loophole-cli-win
    format_overrides:
      - goos: windows
        format: zip
    wrap_in_directory: true
    name_template: >-
      {{ .ProjectName }}-cli_{{ .Version }}_
      {{- if eq .Os "darwin" }}macos{{ else }}{{ title .Os }}{{ end }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
      {{- if .Mips }}_{{ .Mips }}{{ end }}
  - id: desktop
    builds:
      - loophole-desktop
      - loophole-desktop-win
    name_template: >-
      {{ .ProjectName }}-desktop_{{ .Version }}_
      {{- if eq .Os "darwin" }}macos{{ else }}{{ title .Os }}{{ end }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
      {{- if .Mips }}_{{ .Mips }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    wrap_in_directory: true
checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - Merge pull request
      - Merge branch
      - go mod tidy
