package closehandler

import (
	"fmt"
	"io/ioutil"
	"os"
	"os/signal"
	"strings"
	"syscall"

	"github.com/loophole/cli/internal/pkg/cache"
	"github.com/loophole/cli/internal/pkg/communication"
	"golang.org/x/crypto/ssh/terminal"
)

var successfulConnectionOccured bool = false
var terminalState *terminal.State = &terminal.State{}
var interactiveArgs string = ""

//SetupCloseHandler ensures that CTRL+C inputs are properly processed, restoring the terminal state from not displaying entered characters where necessary
func SetupCloseHandler(feedbackFormURL string) chan os.Signal {
	c := make(chan os.Signal)
	signal.Notify(c, os.Interrupt, syscall.SIGTERM)
	terminalState, err := terminal.GetState(int(os.Stdin.Fd()))
	if err != nil {
		communication.LogFatalErr("Error saving terminal state", err)
	}

	go func() {
		<-c
		if terminalState != nil {
			terminal.Restore(int(os.Stdin.Fd()), terminalState)
		}
		communication.PrintGoodbyeMessage()
		if interactiveArgs != "" {
			communication.LogInfo(fmt.Sprintf("Next time, add the following to loophole to start a tunnel with the same settings: %s", interactiveArgs))
			argFile := cache.GetLocalStorageFile("lastArgs", "logs")
			ioutil.WriteFile(argFile, []byte(interactiveArgs), 0644)
		}
		if successfulConnectionOccured {
			communication.PrintFeedbackMessage(feedbackFormURL)
		}
		os.Exit(0)
	}()
	return c
}

//SuccessfulConnectionOccured sets the corresponding boolean to true, enabling the display of the feedback form URL after closing the CLI
func SuccessfulConnectionOccured() {
	successfulConnectionOccured = true
}

//SaveArguments generated by interactive mode to display after closing to teach the user how to get the same results easier next time
func SaveArguments(args []string) {
	interactiveArgs = strings.Join(args, " ")
}
