name: goreleaser build

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - master

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - run: yarn --frozen-lockfile
        working-directory: ./ui/desktop

      - run: yarn build
        working-directory: ./ui/desktop

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release --snapshot --skip-publish --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: binaries
          path: |
            dist/*.tgz
            dist/*.tar.gz
            dist/*.zip
